- backend/swagger.yml
Create swagger documentation for the node-server api
> Api documentation

- frontend/src/components/Header.css
- frontend/src/components/Header.tsx
- frontend/src/components/MainView.css
- frontend/src/components/MainView.tsx
Added header and main view files.
> React layout

- frontend/package-lock.json
- frontend/package.json
- frontend/src/components/BookingView.tsx
- frontend/src/components/GoogleLogin.tsx
- frontend/src/services/authService.ts
- frontend/src/services/axiosConfigurer.ts
- frontend/src/services/bookingService.ts
- frontend/src/services/bookingServiceMock.ts
- frontend/src/services/buildingService.ts
- frontend/src/services/roomService.ts
- frontend/src/types.ts
- Lisätty 4 serviceä: rooms, booking, login/logout, buildings
- Muut testattu ainakin jotenkin toimiviksi paitsi booking, kaikilla on lähinnä tarkoituksena olla esimerkkejä 
- Lisätty axios config, axios kirjasto jolla voi tehdä http pyyntöjä.
- Lisätty perus tyypit frontissa pyöriteltäville entiteeteille, types.ts
- Muokkasin GoogleLogin:in käyttämään authServiceä.
- Muokkasin bookingView:in käyttämään roomsServiceä ja Room -tyyppiä.
> Frontend api services

- frontend/package-lock.json
- frontend/package.json
- frontend/src/components/App.tsx
- frontend/src/components/BookingView.tsx
- frontend/src/components/LogoutButton.tsx
- frontend/src/components/MainView.tsx
- frontend/src/components/NavBar.tsx
- frontend/src/services/axiosConfigurer.ts
- /login renderöi loginkomponentin
- /preferences renderöi preferenssikomponentin
- muut urlit ohjaa booking sivulle
401 vastaukset bäkkendiltä työntää selaimen osoiteriville /login (eli piirtää loginin)
Logout nappula tekee pyynnöön bäkkärille api/auth/logout joka tyhjentää autentikaatiokeksit, ja työntää selaimen osoiteriville /login
> Frontend routing

- backend/src/app.ts
- backend/src/authMiddleware.ts
- backend/src/controllers/buildingsController.ts
- backend/src/controllers/preferencesController.test.ts
- backend/src/controllers/preferencesController.ts
- backend/src/controllers/roomController.ts
- backend/src/controllers/userController.ts
- backend/src/interfaces/buildingData.ts
- backend/src/models/preferences.ts
- backend/src/models/user.ts
- backend/src/routes/preferences.ts
- backend/src/routes/rooms.ts
- backend/src/types/buildingData.ts
- backend/src/types/preferences.ts
- backend/src/types/roomData.ts
- backend/src/types/user.ts
Backend puolen toteutus käyttäjän suosikeista. Mahdollistaa suosikkitalon (myöhemmin myös mahdollisesti muita) asettamisen ja hakemisen käyttäjälle.
**Huom**
Taas tuli aika paljon tähän noita muuttuneita tiedostoja kun päivittelin samalla nuo interfacet typeiksi👀
- GET preferences + testit
- PUT preferences + testit
- Muutamia pieniä muutoksia kuten interfacejen muuttaminen typeksi yms
- ~~Lisää testejä voisi tehdä jos kerkeää~~ Laitankin jossakin kohtaa toisen pr mihin ängen varmaan kaikkee tällästä yleishyödyllistä :)
> Implement backend side of preferences

- backend/src/controllers/booking/currentBookingsController.test.ts
- backend/src/controllers/googleAPI/adminAPI.ts
- backend/src/controllers/googleController.ts
- backend/src/controllers/roomController.ts
- backend/src/routes/rooms.ts
- backend/src/types/roomData.ts
- backend/src/utils/responses.ts
- frontend/src/components/AvailableRoomList.tsx
- frontend/src/types.ts
- Huoneet palautetaan aakkosjärjestyksessä kapasiteetin sijaan
- Muutin huoneen ID = email
- FYI @Jondelele: Jouduin muuttamaan currentBookingsController testiä hieman tästä muutoksesta johtuen, ei kuitenkaan mitään suurempaa
- Poista varatut huoneet backend tuloksista
- Testit (tehdään myöhemmin)
- Kun varaus on tehty, frontti pitäisi laittaa automaattisesti hakemaan vapaat huoneet uudelleen, nyt ei ilmeisesti tee niin🤔
> Backend - Rooms improvements & fixes

- backend/src/controllers/booking/bookingUtils.test.ts
- backend/src/controllers/booking/bookingUtils.ts
- backend/src/controllers/booking/getBookingController.ts
- backend/src/controllers/booking/makeBookingController.test.ts
- backend/src/controllers/booking/makeBookingController.ts
- backend/src/controllers/booking/updateBookingController.ts
- backend/src/controllers/googleAPI/adminAPI.ts
- backend/src/controllers/googleAPI/calendarAPI.ts
- backend/src/controllers/roomController.ts
- backend/src/routes/booking.ts
Tosiaan ajan lisäyksen implementointi ja siinä samassa tein samoilla palikoilla tuon eventIdllä tehtävän haun. Mukana myös "vähän" muita korjauksia yms optimointeja, jota tuli vastaan tätä tehdessä, lähinnä sellaisia, jotka vähentävät toistoa yms :)
- Siirretty `simplifyEventData` omaan tiedostoon ja muokattu sitä hakemaan lisää tietoja huoneesta, jotta saadaan yhtenäiset vastaukset kaikista huonetiedoista
- Pieni korjaus `deleteBookingControlleriin`
- `getBooking` implementoitu, joka hakee varauksen URL:ssä olevalla bookingId:llä ja heittää res.locals myöhemmin tarvittavia tietoja varauksesta
- Ajan lisääminen varaukseen
- Tein sekä ajan lisäämiseen että uuteen varaukseen middlewaren joka katsoo heti alkuun onko huone vapaana haluttuna aikana. Varauksen jälkeen tehdään kuitenkin vielä …
> Backend - Add time to reservation

- frontend/src/components/AvailableRoomList.tsx
- frontend/src/components/BookingView.tsx
- frontend/src/components/CurrentBooking.tsx
- frontend/src/components/util/TimeLeft.tsx
- Ajan lisääminen päivittyy UI:hin
- Varauksen tekeminen poistaa huoneen listasta
- Varauksen poistaminen poistaa varauksen UI:sta
- Aakkosjärjestyksessä
> Booking improvements

- frontend/src/components/AvailableRoomList.tsx
Korjaa ylös-skrollauksen varauksen yhteydessä
> Scroll mainview instead of window on booking

- frontend/src/components/AvailableRoomList.tsx
- frontend/src/components/NavBar.tsx
Alapalkki oli liian alhaalla mobiilinäkymissä, joissa osoiterivi oli näkyvissä
- Css attribuutti sticky, jolla palkki aina alareunassa
- Piti lisätä room listaukseen vähän alamarginaalia ettei viimeinen huone mennyt palkin taakse, näyttääkö ehkä vähän hassulta kun ei ole tuota osoitepalkkia, listaa voi rullata ehkä inasen liian alas.
> Appbar fix

- frontend/public/index.html
https://stackoverflow.com/questions/67301629/pwa-ios-safari-redirect-navbar-height-problem
> Add meta tag for iphone formatting

- frontend/src/components/BookingView.tsx
- frontend/src/components/CurrentBooking.tsx
- Huoneet haetaan nyt uudestaan, kun huone poistettu, jolloin poistettu huone näkyy myös listassa.
- Nappien uudelleenasettelua CurrentBooking:ssa
> Booking view

- frontend/src/components/AvailableRoomList.test.tsx
- frontend/src/components/AvailableRoomList.tsx
- frontend/src/components/CurrentBooking.test.tsx
- frontend/src/components/CurrentBooking.tsx
- frontend/src/theme.ts
Yksikkötestejä lisätty:
- 30min varaaminen
- 60min varaaminen
- Varaukseen lisäajan lisääminen
- Varauksen poistaminen
> Frontend tests

- frontend/src/components/AvailableRoomList.tsx
- frontend/src/components/BookingView.tsx
- frontend/src/components/CurrentBooking.tsx
- frontend/src/components/util/TimeLeft.tsx
Added:
- Features can be expanded/collapsed in multiple rooms at the same time.
- Toggle switch to expand/collapse all room features.
- Disclaimer when booking is not possible due to active booking
- Hide 60min button if the room cannot be booked for that duration
- Remove quick book button when having active booking
- UI updates and alignments
> UI improvements

- backend/src/controllers/booking/currentBookingsController.ts
- backend/src/routes/booking.ts
- backend/src/types/currentBookingData.ts
- frontend/src/components/CurrentBooking.tsx
- frontend/src/services/bookingService.ts
In this same pull request there is Marakkes frontend implementation.
Added nextCalendarEvent to the current booking feature.
Implemented by using until query parameter.
> Current booking nextcalendarevent

- LICENCE
- package-lock.json
- package.json
- Lisäilin kaikkien suoraan käytettyjen riippuvuuksien lisenssit LICENSE tiedostoon
- Poistin ylimääräisiä riippuvuuksia ylimmältä tasolta, koska samat riippuvuudet oli installattu myös frontendiin ja niitä käytetään vain siellä (Axios, Material-ui). Ilmeisesti oli vahingossa asennettu myös tähän kansioon?
> Updated license

- .github/workflows/ci.yml
The old GitHub Actions Gcloud authentication deprecated so I changed it to the new style of authentication.
> Updated gcloud cli auth

- frontend/public/privacypolicy.html
- frontend/public/termsandconditions.html
Lisäsin mainitut dokkarit *lähes* suoraan generaattorista suoraan HTML muodossa, koska ei jaksanut alkaa kikkailemaan :)
Näihin pääsee siis käsiksi laittamalla URL: 
https://zxy.com/privacypolicy.html sekä
https://zxy.com/termsandconditions.html
> Add privacy policy, terms and conditions

- .gitignore
- backend/src/controllers/booking/currentBookingsController.ts
- backend/src/controllers/googleAPI/adminAPI.test.ts
- backend/src/controllers/googleAPI/calendarAPI.test.ts
- backend/src/controllers/roomController.ts
- frontend/public/index.html
- frontend/public/serviceworker.js
Reverts keulacorp/get-a-room#80
> Revert "Code cleaning"

- .gitignore
- backend/src/controllers/booking/currentBookingsController.ts
- backend/src/controllers/googleAPI/adminAPI.test.ts
- backend/src/controllers/googleAPI/calendarAPI.test.ts
- backend/src/controllers/roomController.ts
- backend/src/types/currentBookingData.ts
- frontend/public/index.html
- frontend/public/serviceworker.js
Update production with older code.
Removed minor current booking refactorings and changed so that now also the bookings where the user is creator are shown in Get A Room!
> Update production with older code

- frontend/src/components/AvailableRoomList.test.tsx
- frontend/src/components/AvailableRoomList.tsx
- frontend/src/components/BookingDrawer.tsx
- frontend/src/components/DurationPicker.tsx
- frontend/src/components/PreferencesView.tsx
- frontend/src/components/RoomCard.tsx
- frontend/src/components/SwipeableEdgeDrawer.tsx
- frontend/src/components/login/LoginView.tsx
- frontend/src/theme.ts
Update the AvailableRoomList component to follow new desing, and room booking to follow new desing.
> Book selected time

- frontend/src/components/AvailableRoomList.test.tsx
- frontend/src/components/AvailableRoomList.tsx
- frontend/src/components/BookingDrawer.tsx
- frontend/src/components/BookingView.tsx
- frontend/src/components/DurationPicker.tsx
- frontend/src/components/NavBar.tsx
- frontend/src/components/RoomCard.tsx
- frontend/src/theme.ts
- fetches all rooms, and frontend filters rooms by selected duration.
- add tests for filtering rooms.
- Accessibility
-  Fix color contrast issues.
> filter rooms by selected duration

- backend/src/controllers/booking/updateBookingController.ts
- backend/src/routes/booking.ts
- frontend/src/components/CurrentBooking.tsx
- frontend/src/services/bookingService.ts
Fixed prettier error on previous commit
New button and functionality on current booking-card (To be moved to the bottom menu). "End booking"-button changes the booking end time to current time and ends the booking.
>  Added end booking -feature - FIXED

- frontend/src/components/AvailableRoomList.tsx
- frontend/src/components/BookingDrawer.test.tsx
- frontend/src/components/BookingDrawer.tsx
Implementing functionality of +15 and -15 buttons from editing booking duration. if there is no meetings on the day +15 button is disabled on end of the day.
> Booking change duration

- frontend/src/components/AvailableRoomList.tsx
- frontend/src/components/BookingDrawer.tsx
- frontend/src/components/util/TimeLeft.tsx
The until "xx:30" now always shows the next "xx:30" time instead of disabling the button.
> Booking drawer until buttons - FIXED implementation

- backend/src/controllers/booking/updateBookingController.ts
- frontend/src/components/AlterBookingDrawer.tsx
- frontend/src/components/AvailableRoomList.test.tsx
- frontend/src/components/AvailableRoomList.tsx
- frontend/src/components/BookingDrawer.tsx
- frontend/src/components/BookingView.tsx
- frontend/src/components/CurrentBooking.test.tsx
- frontend/src/components/CurrentBooking.tsx
- frontend/src/components/RoomCard.tsx
- frontend/src/components/util/TimeLeft.test.tsx
- frontend/src/components/util/TimeLeft.tsx
Updated current booking to new design
> Alter booking new style

- backend/src/controllers/booking/makeBookingController.ts
- frontend/src/components/AlterBookingDrawer.tsx
- frontend/src/components/BookingDrawer.tsx
- frontend/src/components/util/TimeLeft.tsx
> fix alter booking bugs

- backend/src/controllers/googleAPI/calendarAPI.ts
- backend/src/controllers/roomController.test.ts
- backend/src/controllers/roomController.ts
- backend/src/types/roomData.ts
- frontend/src/components/BookingView.tsx
- frontend/src/components/BusyRoomList.test.tsx
- frontend/src/components/BusyRoomList.tsx
- frontend/src/components/CurrentBooking.tsx
- frontend/src/components/RoomCard.tsx
- frontend/src/components/util/TimeLeft.tsx
- frontend/src/types.ts
Render rooms that are available in 30 minutes.
> Filter available in 30 min

- frontend/src/components/FilteringDrawer.tsx
Button styling fixed to match figma design
> UI styling for filter buttons fixed

- backend/src/controllers/auth/token.test.ts
> replaced expired test token

- frontend/src/components/App.tsx
- frontend/src/components/BookingView/BookingView.tsx
- frontend/src/components/BookingView/FilteringDrawer.tsx
- frontend/src/components/BuildingList/BuildingList.tsx
- frontend/src/components/SwipeableEdgeDrawer/SwipeableEdgeDrawer.tsx
- frontend/src/components/UserDrawer/UserDrawer.test.tsx
- frontend/src/components/UserDrawer/UserDrawer.tsx
- frontend/src/contexts/UserSettingsContext.tsx
Added context for user settings. Fixed couple of style errors
> Fixing drawer styles and logic

- frontend/src/components/RoomCard/RoomCard.tsx
- frontend/src/types.ts
- frontend/src/util/commonUtils.test.ts
- frontend/src/util/commonUtils.ts
Added floor information for booking convenience.
Also includes a new common utils class for some potentially commonly required utility functions.
> Added floor information to the room in booking view

- frontend/src/components/BusyRoomList/BusyRoomList.tsx
- frontend/src/components/CurrentBooking/CurrentBooking.tsx
- frontend/src/components/RoomCard/RoomCard.tsx
- frontend/src/enums.ts
- frontend/src/theme_2024.ts
Added some styling to help separating the current and future bookings (green = currently ongoing,  yellow = future)
> Added some styling to separate current and future bookings of the user

- frontend/src/components/AvailableRoomList/AvailableRoomList.test.tsx
- frontend/src/components/AvailableRoomList/AvailableRoomList.tsx
- frontend/src/components/BookingView/BookingView.tsx
- frontend/src/components/MainView/MainView.tsx
- frontend/src/services/preferencesService.ts
Small refactor on way the preferences are loaded based on geolocation permission. Results in less preferences updates, meaning less /preferences api calls.
Also removed some unused preference variables.
> Refactoring preferences loading
